KEY_PATH="~/.ssh/xxx.pem"
AWS_EC2_HOST="ec2-xxx-xxx-xxx-xxx.ap-northeast-1.compute.amazonaws.com"

ANSWER_CHECK_SERVER_STATUS_PS_COUNT=0

ANSWER_CHECK_SERVER_STATUS_MEM_TOTAL_MIB=000.0
ANSWER_CHECK_SERVER_STATUS_MEM_USED_MIB=000.0

ANSWER_CHECK_SERVER_STATUS_DISK_TOTAL_GB="0.0G"
ANSWER_CHECK_SERVER_STATUS_DISK_USED_GB="0.0G"
