# This must be loaded as a `pathproto.content.Project`

situation: <
  situation_id: "TtC8-bEVewTqIKtNZgu_O"
  translation_file: "./tasks/ts_node/locales/translations.yml"

  generation_config: <
    flag: "SITUATION=TS_NODE"
  >
  root_dir_name: "bootcamp_ts_node"
>
